database:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521/eks
  user: IBS
  pass: IBS

hibernate:
  dialect: org.hibernate.dialect.Oracle10gDialect
  jdbc.batch_size: 1000
  order_inserts: true
  order_updates: true
  enable_lazy_load_no_trans: true
  show_sql: false
  format_sql: false
  id.new_generator_mappings: false

logging:
  level:
    org.hibernate.type:
      descriptor:
        sql.BasicBinder: INFO

security:
  auth:
    privateKey: Njb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJhdGkiOiI0ZW

server:
  servlet:
    context-path: /stockanalizer